In [34]:
%pip install gensim

Requirement already satisfied: gensim in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from gensim) (2.4.2)
Requirement already satisfied: scipy>=1.7.0 in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from gensim) (1.17.1)
Requirement already satisfied: smart_open>=1.8.1 in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [36]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [37]:
vking = wv['king']

In [38]:
vking.shape

(300,)

In [39]:
import pandas as pd 
messages = pd.read_csv('spam.csv', sep= ',', names = ['label', 'message'], encoding= 'latin-1', usecols=(0,1))

In [40]:
messages

     label                                            message
0       v1                                                 v2
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5573 rows x 2 columns]

In [41]:
messages = messages.drop(0,)
messages

     label                                            message
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
5      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [42]:
import re

In [43]:
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [46]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'].iloc[i])
    review = review.lower()
    review = review.split()

    review = [lemma.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [48]:
import nltk

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess  ##important

In [52]:
## simple_preprocess converts a document into a list of lower case tokens ignoring tokens thats are too short or too long.

In [56]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
           words.append(simple_preprocess(sent))